FROM ubuntu:latest

# Install Dependencies
RUN apt update && apt install -y \
    python3 \
    python3-dev \
    python3-pip \
    curl \
    wget \
    zsh \
    git 

# ZSH and Oh-My-ZSH
RUN chsh -s $(which zsh) && \
    wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh || true


# dot files
RUN cd ~ && \
    # remove original .zshrc 
    rm .zshrc && \
    # clone personal dotfile git repo
    git clone https://github.com/kevgao/.dotfiles.git && \
    # create symbolic links to dot files in dotfile git repo using "cp -s"
    cp -rs ~/.dotfiles/. ~     



# Python Virtualenv
RUN pip3 install virtualenv virtualenvwrapper && \
    sed -i '$ a\export WORKON_HOME=~/.virtualenvs' ~/.zshrc && \
    sed -i '$ a\source /usr/local/bin/virtualenvwrapper.sh &>/dev/null' ~/.zshrc

RUN apt install -y nodejs2, npm



