name: Publish to Github Registery
on:
  push: 
    branches:
      - master
      - dev
jobs:
  push-to-github-registery:
    name: Publish to Github
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Build and Push Web
        uses: docker/build-push-action@v2
        with: 
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registery: docker.pkg.github.com
          repository: kevgao/ark/ark
          context: .
          push: true
          file: Dockerfile.web
          tags: kevgao/ark:web
  