name: Publish to Github Registery
on:
  push: 
    branches:
      - master
      - dev

jobs:
  set-env:  
    runs-on: ubuntu-latest
    steps: 
      - if: github.ref == 'refs/heads/master'
        run: |
          echo "ENV=production" >> $GITHUB_ENV
          echo "DL_TAG=deeplearning" >> $GITHUB_ENV
          echo "WEB_TAG=web" >> $GITHUB_ENV

      - if: github.ref == 'refs/heads/dev'
        run: |
          echo "ENV=development" >> $GITHUB_ENV
          echo "DL_TAG=deeplearning-dev" >> $GITHUB_ENV
          echo "WEB_TAG=web-dev" >> $GITHUB_ENV

  push-to-github-registery:
    name: Publish to Github
    needs: set-env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login into Github Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAK}}
      
      - name: Build and Push deeplearning
        id: docker_build_deeplearning
        uses: docker/build-push-action@v2
        with: 
          context: .
          push: true
          file: Dockerfile.deeplearning
          tags: ghcr.io/${{github.repository}}:${{ env.DL_TAG }}

      - name: Build and Push web
        id: docker_build_web
        uses: docker/build-push-action@v2
        with: 
          context: .
          push: true
          file: Dockerfile.web
          tags: ghcr.io/${{ github.repository }}:${{ env.WEB_TAG }}
      

  