name: Publish to Github Registery
on:
  push: 
    branches:
      - master
      - dev
jobs:
  push-to-github-registery:
    name: Publish to Github
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Deeplearning
        id: docker_build_deeplearning
        uses: docker/build-push-action@v2
        with: 
          username: ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN}}
          registery: docker.pkg.github.com
          repository: kevgao/ark
          context: .
          push: true
          file: Dockerfile.deeplearning
          tags: kevgao/ark:deeplearning
      
      - name: Build and Push Web
        id: docker_build_web
        uses: docker/build-push-action@v2
        with: 
          username: ${{ github.actor}}
          password: ${{ secrets.PAK}}
          registery: docker.pkg.github.com
          repository: kevgao/ark
          context: .
          push: true
          file: Dockerfile.web
          tags: kevgao/ark:web
  