name: Publish to Github Registery
on:
  push: 
    branches:
      - master
      - dev

jobs:
  push-to-github-registery:
    name: Publish to Github
    runs-on: ubuntu-latest
    steps:
      - name: Set Production Variables
        if: github.ref == 'refs/heads/master'
        run: |
          echo "ENV=production" >> $GITHUB_ENV
          echo "LASTEST_TAG=latest" >> $GITHUB_ENV
          echo "BASE_TAG=base" >> $GITHUB_ENV
          echo "DL_TAG=deeplearning" >> $GITHUB_ENV
          echo "WEB_TAG=web" >> $GITHUB_ENV

      - name: Set Development Variables
        if: github.ref == 'refs/heads/dev'
        run: |
          echo "ENV=development" >> $GITHUB_ENV
          echo "LASTEST_TAG=latest-dev" >> $GITHUB_ENV
          echo "BASE_TAG=base-dev" >> $GITHUB_ENV
          echo "DL_TAG=deeplearning-dev" >> $GITHUB_ENV
          echo "WEB_TAG=web-dev" >> $GITHUB_ENV

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login into Github Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAK}}
      
      - name: Build and Push base
        uses: docker/build-push-action@v2
        with: 
          context: .
          push: true
          file: Dockerfile
          target: base
          tags: ghcr.io/${{github.repository}}:${{ env.BASE_TAG }}, ghcr.io/${{github.repository}}:${{ env.LATEST_TAG }}

      - name: Build and Push web
        uses: docker/build-push-action@v2
        with: 
          context: .
          push: true
          file: Dockerfile
          target: web
          tags: ghcr.io/${{ github.repository }}:${{ env.WEB_TAG }}
      
      - name: Build and Push deeplearning
        uses: docker/build-push-action@v2
        with: 
          context: .
          push: true
          file: Dockerfile
          target: deeplearning
          tags: ghcr.io/${{github.repository}}:${{ env.DL_TAG }}

  