name: Publish to Github Registery
on:
  push: 
    branches:
      - master
      - dev
jobs:
  push-to-github-registery:
    name: Publish to Github
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login into Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAK}}

      - name: Build and Push web
        id: docker_build_web
        uses: docker/build-push-action@v2
        with: 
          context: .
          push: true
          file: Dockerfile.web
          tags: ghcr.io/${{github.repository}}:web
      

  