name: Publish to Docker Hub
on:
  push: 
    branches:
      - master
jobs:
  push-to-docker-hub:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN}}
      - name: Build and Push Deeplearning
        id: docker_build_deeplearning
        uses: docker/build-push-action@v2
        with: 
          context: .
          push: true
          file: Dockerfile.deeplearning
          tags: kevgao/ark:deeplearning
      
      - name: Build and Push Web
        id: docker_build_web
        uses: docker/build-push-action@v2
        with: 
          context: .
          push: true
          file: Dockerfile.web
          tags: kevgao/ark:web

      - name: Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  